server:
  servlet:
    context-path: /cas
    session:
      timeout: 3600m

# Spring config
spring:
  application:
    name: cas
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cas?useUnicode=true&characterEncoding=urf8
    username: root
    password: 123456
  mvc:
    data-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# Mybatis configuration
mybatis:
  type-aliases-package: com.tju.cas.entity,com.tju.cas.entity.vo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true

# Logging configuration
debug: true
logging:
  file: test.log
  level:
    com.tju.cas: debug

